apiVersion: apps/v1
kind: Deployment
metadata:
  name: clinical-service
  namespace: medicate
spec:
  replicas: 2
  selector:
    matchLabels:
      app: clinical-service
  template:
    metadata:
      labels:
        app: clinical-service
    spec:
      containers:
        - name: clinical-service
          image: clinical-service:v1
          imagePullPolicy: IfNotPresent
          ports:
            - containerPort: 5000

          envFrom:
          - secretRef:
              name: clinical-medical-service-secrets