apiVersion: v1
kind: Secret
metadata:
  name: appointment-service-secrets
  namespace: medicate
type: Opaque
data:
  PORT: NTAwMw==
  MONGO_URI: bW9uZ29kYjovL21vbmdvZGI6MjcwMTcvbWVkaWNhdGVfYXBwb2ludG1lbnRz
  REDIS_HOST: cmVkaXMtc2VydmljZQ==
  REDIS_PORT: NjM3OQ==
  REDIS_PASSWORD: ""
  AGORA_APP_ID: ZTdmNmU5YWVlY2YxNGIyYmExMGUzZjQwYmU5ZjU2ZTc=
  AGORA_APP_CERTIFICATE: ZmI5MGVjODg2OTdlNDNhNDg5YWY3YmUwODViM2VhNTk=