apiVersion: v1
kind: Secret
metadata:
  name: user-identity-service-secrets
  namespace: medicate
type: Opaque
data:
  NODE_ENV: cHJvZHVjdGlvbg==
  PORT: MzAwMQ==
  MONGO_URI: bW9uZ29kYjovL21vbmdvZGI6MjcwMTcvbWVkaWNhdGVfdXNlcnM=
  JWT_SECRET: eW91cl9zdXBlcl9zZWNyZXRfamp0X2tleV9jaGFuZ2VfdGhpc19pbl9wcm9kdWN0aW9u
  JWT_EXPIRES_IN: MTVt
  JWT_REFRESH_SECRET: eW91cl9zdXBlcl9zZWNyZXRfcmVmcmVzaF9rZXlfY2hhbmdlX3RoaXNfdG9v
  JWT_REFRESH_EXPIRES_IN: N2Q=