apiVersion: v1
kind: Secret
metadata:
  name: web-client-secrets
  namespace: medicate
type: Opaque
data:
  REACT_APP_APPOINTMENT_SERVICE_URL: aHR0cDovL2FwcG9pbnRtZW50LXNlcnZpY2U6NTAwMw==
  REACT_APP_CLINICAL_SERVICE_URL: aHR0cDovL2NsaW5pY2FsLXNlcnZpY2U6NTAwMA==
  REACT_APP_TRANSACTION_SERVICE_URL: aHR0cDovL3RyYW5zYWN0aW9uLW5vdGlmeS1zZXJ2aWNlOjMwMDM=