apiVersion: v1
kind: Service
metadata:
  name: clinical-medical-service
  
  labels:
    io.kompose.service: clinical-medical-service
spec:
  selector:
    io.kompose.service: clinical-medical-service
  ports:
    - port: 3002
      targetPort: 3002
