apiVersion: v1
kind: Service
metadata:
  name: mongo-transaction
  
  labels:
    io.kompose.service: mongo-transaction
spec:
  selector:
    io.kompose.service: mongo-transaction
  ports:
    - port: 27017
      targetPort: 27017
  clusterIP: None
