apiVersion: v1
kind: Secret
metadata:
  name: medicate-secrets
  namespace: medicate
type: Opaque
stringData:
  MONGO_URI: "mongodb://admin:admin123@mongodb-service:27017/medicate?authSource=admin"
  REDIS_PASSWORD: ""
  AGORA_APP_CERTIFICATE: "fb90ec88697e43a489af7be085b3ea59"
