apiVersion: apps/v1
kind: Deployment
metadata:
  name: appointment-service
  namespace: medicate
  labels:
    app: appointment-service
spec:
  replicas: 2
  selector:
    matchLabels:
      app: appointment-service
  template:
    metadata:
      labels:
        app: appointment-service
    spec:
      containers:
      - name: appointment-service
        image: medicate-appointment-service:latest
        imagePullPolicy: IfNotPresent
        ports:
        - containerPort: 5003
        envFrom:
        - secretRef:
            name: appointment-service-secrets
---
apiVersion: v1
kind: Service
metadata:
  name: appointment-service
  namespace: medicate
spec:
  selector:
    app: appointment-service
  ports:
  - protocol: TCP
    port: 5003
    targetPort: 5003
  type: ClusterIP