apiVersion: apps/v1
kind: Deployment
metadata:
  name: transaction-notify-deployment
  namespace: default
spec:
  replicas: 1
  selector:
    matchLabels:
      app: transaction-notify
  template:
    metadata:
      labels:
        app: transaction-notify
    spec:
      containers:
      - name: transaction-notify
        image: medicate-transaction-service:latest
        imagePullPolicy: IfNotPresent  # Uses your local Docker image
        ports:
        - containerPort: 3003
        envFrom:
        - secretRef:
            name: transaction-service-secret # This auto-loads your .env file into the container!

---
apiVersion: v1
kind: Service
metadata:
  name: transaction-notify-service
  namespace: default
spec:
  type: LoadBalancer 
  selector:
    app: transaction-notify
  ports:
    - protocol: TCP
      port: 3003       # Port on your local machine
      targetPort: