#!/bin/bash
# UI Component Conversion Helper Script
# This script lists all .tsx files in the ui directory that need conversion

echo "=================================="
echo "UI Components Needing Conversion"
echo "=================================="
echo ""
echo "Location: /src/app/components/ui/"
echo ""
echo "Files to convert from .tsx to .jsx:"
echo ""

# List of UI component files that typically need conversion
components=(
  "accordion.tsx"
  "alert-dialog.tsx"
  "alert.tsx"
  "aspect-ratio.tsx"
  "avatar.tsx"
  "badge.tsx"
  "breadcrumb.tsx"
  "button.tsx"
  "calendar.tsx"
  "card.tsx"
  "carousel.tsx"
  "chart.tsx"
  "checkbox.tsx"
  "collapsible.tsx"
  "command.tsx"
  "context-menu.tsx"
  "dialog.tsx"
  "drawer.tsx"
  "dropdown-menu.tsx"
  "form.tsx"
  "hover-card.tsx"
  "input-otp.tsx"
  "input.tsx"
  "label.tsx"
  "menubar.tsx"
  "navigation-menu.tsx"
  "pagination.tsx"
  "popover.tsx"
  "progress.tsx"
  "radio-group.tsx"
  "resizable.tsx"
  "scroll-area.tsx"
  "select.tsx"
  "separator.tsx"
  "sheet.tsx"
  "sidebar.tsx"
  "skeleton.tsx"
  "slider.tsx"
  "sonner.tsx"
  "switch.tsx"
  "table.tsx"
  "tabs.tsx"
  "textarea.tsx"
  "toggle-group.tsx"
  "toggle.tsx"
  "tooltip.tsx"
)

count=0
for component in "${components[@]}"; do
  ((count++))
  echo "$count. $component → ${component%.tsx}.jsx"
done

echo ""
echo "Total: $count files"
echo ""
echo "=================================="
echo "Conversion Pattern"
echo "=================================="
echo ""
echo "For each file:"
echo "1. Remove 'interface' and 'type' declarations"
echo "2. Remove ': Type' annotations"
echo "3. Remove 'React.FC<Props>' patterns"
echo "4. Remove '<Type>' generic parameters"
echo "5. Keep all JSX, logic, and imports unchanged"
echo ""
echo "Example:"
echo "  BEFORE: const Button = React.forwardRef<HTMLButtonElement, ButtonProps>("
echo "  AFTER:  const Button = React.forwardRef("
echo ""
echo "=================================="
echo ""
echo "Note: These conversions are optional. The app works with mixed .tsx/.jsx files."
echo "Vite automatically handles both TypeScript and JavaScript."
echo ""
